Use mesh_coloration from kwiver.
Kitware/TeleSculptor pull request #403
Opened 2020-10-27 19:48 UTC by danlipsa

2020-10-27 19:49 UTC, danlipsa commented
@mleotta These are corresponding changes in Telesculptor.

2020-10-28 14:32 UTC, mleotta requested changes
I made a few very minor formatting suggestions.  Generally this looks good, but it will need to wait until the KWIVER branch lands.

2020-10-28 14:32 UTC, mleotta commented on gui/ColorizeSurfaceOptions.h
> +namespace kwiver { namespace arrows { namespace vtk {
I would prefer each namespace start on a new line

2020-10-28 14:32 UTC, mleotta commented on gui/MainWindow.h
> +namespace kwiver { namespace arrows { namespace vtk {
start namespaces on new lines

2020-10-28 14:32 UTC, mleotta commented on gui/WorldView.h
> +namespace kwiver { namespace arrows { namespace vtk {
namespaces on new lines

2020-11-09 14:48 UTC, danlipsa commented
@mleotta TeleSculptor now picks up kwiver master and has changes required for mesh_coloration leaving in kwiver.

2020-11-18 15:04 UTC, mleotta commented
@danlipsa this is failing CI because of a recent change in KWIVER that now requires CMake >= 3.15.  Travis CI uses Ubuntu 18.04, which comes with CMake 3.10.  I've updated the Travis CI scripts to download a newer CMake.

Can you merge in the latest TeleSculptor master and push this again to see if that gets CI working again on this branch?

2020-11-18 15:14 UTC, danlipsa commented
@mleotta I rebased on master so lets see now.

2020-11-18 18:46 UTC, merged