Fix highlighting of selected point
Kitware/TeleSculptor pull request #481
Opened 2021-05-17 18:25 UTC by mwoehlke-kitware

Replace "duplicated" (and wrong, at least since introducing registration points as child items) logic in `GroundControlPointsView` to get the id of a point from its model index and instead use the helper function from the model (which is correctly implemented) to do so.

Fixes #478.

2021-05-18 16:05 UTC, mleotta requested changes
This is an improvement, I am no longer seeing the wrong GCP selected, but sometimes when selecting a frame underneath a GCP I get no highlighted point, other times it highlights the correct point.

2021-05-18 16:35 UTC, mwoehlke-kitware commented
I didn't notice any issues. Can you please provide steps to reproduce?

2021-05-18 17:24 UTC, mleotta commented
1. Open TeleSculptor and add 4 GCPs in the World view
2. In the Camera view add 1 CRP to each of the GCPs in the same order
3. Expand the tree view for each GCP

I can highlight GCPs 0 and 1 by selecting either the GCP or the frame number below it (frame -1 since no video loaded).  For GCPs 2 and 3 I can highlight only by selecting the GCP.  If I select the frame number nothing is highlighted.

I've done this on a real video too, so it's not related to the frame being -1.

2021-05-19 15:49 UTC, mwoehlke-kitware commented
Huh... okay, can reproduce, no clue why 2/3 would be different from 0/1 though...

2021-05-19 16:52 UTC, mwoehlke-kitware commented
Should be fixed...

2021-05-19 17:29 UTC, merged